Add meeting link to talk
10PinesLabs/smart-open-space pull request #11
Opened 2022-05-16 19:24 UTC by IngErnestoAlvarez

2022-05-16 19:58 UTC, gperez-10pines approved these changes
Aprobado con comentarios.

2022-05-16 19:58 UTC, gperez-10pines commented on front/src/shared/MyForm.js
> +const MyFieldMeeting = (props) => (
MyFieldMeeting no seria un buen nombre. 

El problema con Meeting es que no sabemos si se refiere a un nombre, a una url, o que. Y por su parte MyField no agrega valor (yo diria que al contrario).

Yo honestamente lo llamaria LinkField.

2022-05-16 19:58 UTC, gperez-10pines commented on back/src/main/resources/db/migration/V1_3__link_for_talk.sql
> +    add column if not exists meeting varchar(255);
yo no quiero bloquear el PR, pero aca tambien espararia ver meetingLink. Porque meeting es una palabra sin contexto. 

Talk > meeting. Hay que pensarlo un poco para saber que es. En cambio con meetingLink la intencion es mas clara.

2022-05-17 15:32 UTC, fdodino approved these changes
Todo liso! Ahí te dejé un fix de un typo, el resto 💯  puntos

2022-05-17 15:32 UTC, fdodino commented on front/src/helpers/validateUrl.js
> +  return 'La url no es valida';
```suggestion
  return 'La url no es válida';
```

2022-05-17 17:06 UTC, JuanFdS requested changes
Dejé un par de comentarios no bloqueantes.
Lo único bloqueante es:
Además de validar en el front, ¿estás validando en el backend que la URL sea válida?

2022-05-17 17:06 UTC, JuanFdS commented on front/src/helpers/validateUrl.js
> +  if (!value) return;
pregunta, en que casos `value` puede ser null o undefined? no arranca siendo un string vacío?

2022-05-17 17:12 UTC, IngErnestoAlvarez commented on front/src/helpers/validateUrl.js
> +  if (!value) return;
Puede ser undefined si no se seteó nada en el campo

2022-05-17 17:34 UTC, merged